ALTER TABLE services
    ADD COLUMN price      NUMERIC(10,2) NOT NULL DEFAULT 0,
    ADD COLUMN currency   VARCHAR(3) NOT NULL DEFAULT 'TRY',
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE services ALTER COLUMN price DROP DEFAULT;
ALTER TABLE services ALTER COLUMN currency DROP DEFAULT;
